### ISSUE TITLE
Creating the expense tracker

### ISSUE THREAD

**Issue by UofTTeam2** [UofTTeam2/TravIS#10]
# User Story

**As** a frequent traveler, 
**I want** to be able to create and manage my trip itineraries easily using the TravIs application,
**so that** I can efficiently plan and organize my travels.

---

### Expense Tracker

- **Given** that I have added costs to my itinerary items,
- **When** I view the "Expense Tracker" section,
- **Then** I should see a breakdown of the total trip cost, categorized by items such as accommodation, transportation, and activities.

**Comment by average-kirigiri-enjoyer** [comment]
in handlebars;
- [x] Implement chart.js to render expense data (pie chart, grouped by itinerary item category (and maybe also section)

in (controller) javascript;
- [x] summed expenses of each itinerary item category (accommodation, transportation, food, etc.) is packaged into an array (or object), and added to the data rendered to the 'view-itinerary' & 'view-itinerary-public' pages
