### ISSUE TITLE
Editing a trip

### ISSUE THREAD

**Issue by UofTTeam2** [UofTTeam2/TravIS#2]
# User Story

**As** a frequent traveler, 
**I want** to be able to create and manage my trip itineraries easily using the TravIs application,
**so that** I can efficiently plan and organize my travels.

---

### Trip Creation and Itinerary Builder
- **Given** that I have already created a trip,
- **When** I edit the trip details,
- **Then** I should be able to update the trip name, start date, end date, and description.

**Comment by average-kirigiri-enjoyer** [comment]
in handlebars;
- [x] Build partials to construct sections, categories, and items when given itinerary data
  - [x] View page displays all existing details for each item (link applied to header if it exists), with all other item details & categories with no items being hidden
  - [x] Edit page displays all possible details for existing items (link & header are separate, image is an input element that accepts a file), even if they have no data, and all categories, even if they have no items
    - [x] Displays current image for each item (if it exists), alongside a preview box for the image the user wants to upload
- [x] Add jQuery datepicker to start / end dates
- [x] Add jQuery timepicker to start / end times
- [x] Add delete buttons for sections & itinerary items
  - [x] Should create a pop-up for deletion confirmation
- [x] Add button to clear selected image from image inputs in edit mode
- [x] Add button to clear current image from an itinerary item / title card in edit mode
- [x] Add chart.js expense summary to view page (either a link to a dedicated page, or display the chart on the page)
- [x] Create handlebars page to serve as a redirect for bad requests
  - [x] Should have a message saying "Oops, could not retrieve that page", plus a redirect link to the landing page ('/')

in (public) javascript;
- [x] Throws an error if the user tries to input a file that is not an image, or exceeds 10 MB in size (piggyback off Ehsan's error modal)
- [x] Render a preview of the image the user uploads while in edit mode
  - [x] If the page is refreshed after an image is uploaded, clear the chosen image (or re-render the preview)
- [x] When a user goes to delete a section / item, the data is appropriately packaged and a DELETE fetch request is made, + the appropriate element is removed from the page
- [x] Upon clicking the "save" button in edit mode, a series of for loops (or forEach loops) packages the value of each element under each itinerary item (including the fields that are not filled out) into objects, and sends the collated data to the database via a PUT request _(an entry for each item should already exist; just find the right ID and update the rest of the fields appropriately)_
  - [x] Uses multer to upload all newly-attached image files (should not re-upload already-existing images)
  - [x] Follows up multer uploads with the above for / forEach loops to collate data
  - [x] When it comes to the image properties, performs the following;
    - Checks if there is an image selected in the image input -> uses that as the image property
    - If there is no image selected, check if there is an image already attached -> uses that as image property
    - If there is no image selected, nor is there an image already attached -> sets image property to an empty string
- [x] Upon clicking the "+" button under a specific category in edit mode, that category should be saved to a variable, and attached to a POST request made to the server to create a new itinerary item
  - [x] A new itinerary item should be dynamically generated and appended to the appropriate category _(this way, you don't have to re-render the entire page)_
  - [x] Implement identical functionality for the "create new section" button
- [x] Upon clicking the 'edit' button in view mode, a GET request is made using the ID in a route parameter for a specific trip
- [x] Clicking 'remove chosen image' button removes the chosen file from the appropriate input, and returns the preview image source file to the stock photo
- [x] Clicking 'remove current image' button deletes the 'current image' img element _(this way, when the user saves, it gets flagged as having no current image)_
 
in (controller) javascript;
- [x] When files are uploaded via multer, it is saved to a server-side folder, generates new, random names for each file, appends the new name to an array, and returns the array to the front end as a JSON response
- [x] Refactor routes such that the API routing sends a user to a specific page after performing the appropriate actions, and then arriving at that page triggers a GET request that renders the appropriate handlebars page & data
- [x] Add authentication middleware described below to all appropriate trip routes

in utils;
- [x] Create authentication middleware to check if the trip a user is trying to access is associated with their account by comparing the user_id in session storage to the user_id of the selected trip
  - [x] If they match, continue with the routing process. If they don't, redirect the user to the 'bad request' page

**Comment by UofTTeam2** [comment]
@average-kirigiri-enjoyer I have done the rest of the tasks related to the middleware (also added the bad-request to be redirected to) and ✅ them. please close the issue whenever you merged the branch
